export const ILLER = [
  {ad:"Adana",ilceler:["Aladağ","Ceyhan","Çukurova","Feke","İmamoğlu","Karaisalı","Karataş","Kozan","Pozantı","Saimbeyli","Sarıçam","Seyhan","Tufanbeyli","Yumurtalık","Yüreğir"]},
  {ad:"Adıyaman",ilceler:["Merkez","Besni","Çelikhan","Gerger","Gölbaşı","Kahta","Samsat","Sincik","Tut"]},
  {ad:"Afyonkarahisar",ilceler:["Merkez","Başmakçı","Bayat","Bolvadin","Çay","Çobanlar","Dazkırı","Dinar","Emirdağ","Hocalar","İhsaniye","İscehisar","Kızılören","Sandıklı","Sinanpaşa","Sultandağı","Şuhut"]},
  {ad:"Ağrı",ilceler:["Merkez","Diyadin","Doğubayazıt","Eleşkirt","Hamur","Patnos","Taşlıçay","Tutak"]},
  {ad:"Amasya",ilceler:["Merkez","Göynücek","Gümüşhacıköy","Hamamözü","Merzifon","Suluova","Taşova"]},
  {ad:"Ankara",ilceler:["Altındağ","Ayaş","Bala","Beypazarı","Çamlıdere","Çankaya","Çubuk","Elmadağ","Etimesgut","Evren","Gölbaşı","Güdül","Haymana","Kalecik","Kazan","Keçiören","Kızılcahamam","Mamak","Nallıhan","Polatlı","Pursaklar","Sincan","Şereflikoçhisar","Yenimahalle"]},
  {ad:"Antalya",ilceler:["Akseki","Aksu","Alanya","Demre","Döşemealtı","Elmalı","Finike","Gazipaşa","Gündoğmuş","İbradı","Kaş","Kemer","Kepez","Konyaaltı","Korkuteli","Kumluca","Manavgat","Muratpaşa","Serik"]},
  {ad:"Artvin",ilceler:["Merkez","Ardanuç","Arhavi","Borçka","Hopa","Murgul","Şavşat","Yusufeli"]},
  {ad:"Aydın",ilceler:["Efeler","Bozdoğan","Buharkent","Çine","Didim","Germencik","İncirliova","Karacasu","Karpuzlu","Koçarlı","Köşk","Kuşadası","Kuyucak","Nazilli","Söke","Sultanhisar","Yenipazar"]},
  {ad:"Balıkesir",ilceler:["Altıeylül","Ayvalık","Balya","Bandırma","Bigadiç","Burhaniye","Dursunbey","Edremit","Erdek","Gömeç","Gönen","Havran","İvrindi","Karesi","Kepsut","Manyas","Marmara","Savaştepe","Sındırgı","Susurluk"]},
  {ad:"Bilecik",ilceler:["Merkez","Bozöyük","Gölpazarı","İnhisar","Osmaneli","Pazaryeri","Söğüt","Yenipazar"]},
  {ad:"Bingöl",ilceler:["Merkez","Adaklı","Genç","Karlıova","Kiğı","Solhan","Yayladere","Yedisu"]},
  {ad:"Bitlis",ilceler:["Merkez","Adilcevaz","Ahlat","Güroymak","Hizan","Mutki","Tatvan"]},
  {ad:"Bolu",ilceler:["Merkez","Dörtdivan","Gerede","Göynük","Kıbrıscık","Mengen","Mudurnu","Seben","Yeniçağa"]},
  {ad:"Burdur",ilceler:["Merkez","Ağlasun","Altınyayla","Bucak","Çavdır","Çeltikçi","Gölhisar","Karamanlı","Kemer","Tefenni","Yeşilova"]},
  {ad:"Bursa",ilceler:["Osmangazi","Yıldırım","Nilüfer","Büyükorhan","Gemlik","Gürsu","Harmancık","İnegöl","İznik","Karacabey","Keles","Kestel","Mudanya","Mustafakemalpaşa","Orhaneli","Orhangazi","Yenişehir"]},
  {ad:"Çanakkale",ilceler:["Merkez","Ayvacık","Bayramiç","Biga","Bozcaada","Çan","Eceabat","Ezine","Gelibolu","Gökçeada","Lapseki","Yenice"]},
  {ad:"Çankırı",ilceler:["Merkez","Atkaracalar","Bayramören","Çerkeş","Eldivan","Ilgaz","Kızılırmak","Korgun","Kurşunlu","Orta","Şabanözü","Yapraklı"]},
  {ad:"Çorum",ilceler:["Merkez","Alaca","Bayat","Boğazkale","Dodurga","İskilip","Kargı","Laçin","Mecitözü","Oğuzlar","Ortaköy","Osmancık","Sungurlu","Uğurludağ"]},
  {ad:"Denizli",ilceler:["Merkezefendi","Pamukkale","Acıpayam","Babadağ","Baklan","Bekilli","Beyağaç","Bozkurt","Buldan","Çal","Çameli","Çardak","Çivril","Güney","Honaz","Kale","Sarayköy","Serinhisar","Tavas"]},
  {ad:"Diyarbakır",ilceler:["Bağlar","Sur","Kayapınar","Yenişehir","Bismil","Çermik","Çınar","Çüngüş","Dicle","Eğil","Ergani","Hani","Hazro","Kocaköy","Kulp","Lice","Silvan"]},
  {ad:"Edirne",ilceler:["Merkez","Enez","Havsa","İpsala","Keşan","Lalapaşa","Meriç","Süloğlu","Uzunköprü"]},
  {ad:"Elazığ",ilceler:["Merkez","Ağın","Alacakaya","Arıcak","Baskil","Karakoçan","Keban","Kovancılar","Maden","Palu","Sivrice"]},
  {ad:"Erzincan",ilceler:["Merkez","Çayırlı","İliç","Kemah","Kemaliye","Otlukbeli","Refahiye","Tercan","Üzümlü"]},
  {ad:"Erzurum",ilceler:["Palandöken","Yakutiye","Aziziye","Aşkale","Çat","Hınıs","Horasan","İspir","Karayazı","Köprüköy","Narman","Oltu","Olur","Pasinler","Pazaryolu","Şenkaya","Tekman","Tortum","Uzundere"]},
  {ad:"Eskişehir",ilceler:["Odunpazarı","Tepebaşı","Alpu","Beylikova","Çifteler","Günyüzü","Han","İnönü","Mahmudiye","Mihalgazi","Mihalıççık","Sarıcakaya","Seyitgazi","Sivrihisar"]},
  {ad:"Gaziantep",ilceler:["Şahinbey","Şehitkamil","Araban","İslahiye","Karkamış","Nizip","Nurdağı","Oğuzeli","Yavuzeli"]},
  {ad:"Giresun",ilceler:["Merkez","Alucra","Bulancak","Çamoluk","Çanakçı","Dereli","Doğankent","Espiye","Eynesil","Görele","Güce","Keşap","Piraziz","Şebinkarahisar","Tirebolu","Yağlıdere"]},
  {ad:"Gümüşhane",ilceler:["Merkez","Kelkit","Köse","Kürtün","Şiran","Torul"]},
  {ad:"Hakkari",ilceler:["Merkez","Çukurca","Derecik","Şemdinli","Yüksekova"]},
  {ad:"Hatay",ilceler:["Antakya","Defne","İskenderun","Altınözü","Arsuz","Belen","Dörtyol","Erzin","Hassa","Kırıkhan","Kumlu","Payas","Reyhanlı","Samandağ","Yayladağı"]},
  {ad:"Isparta",ilceler:["Merkez","Aksu","Atabey","Eğirdir","Gelendost","Gönen","Keçiborlu","Senirkent","Sütçüler","Şarkikaraağaç","Uluborlu","Yalvaç","Yenişarbademli"]},
  {ad:"İstanbul",ilceler:["Adalar","Arnavutköy","Ataşehir","Avcılar","Bağcılar","Bahçelievler","Bakırköy","Başakşehir","Bayrampaşa","Beşiktaş","Beykoz","Beylikdüzü","Beyoğlu","Büyükçekmece","Çatalca","Çekmeköy","Esenler","Esenyurt","Eyüpsultan","Fatih","Gaziosmanpaşa","Güngören","Kadıköy","Kağıthane","Kartal","Küçükçekmece","Maltepe","Pendik","Sancaktepe","Sarıyer","Silivri","Sultanbeyli","Sultangazi","Şile","Şişli","Tuzla","Ümraniye","Üsküdar","Zeytinburnu"]},
  {ad:"İzmir",ilceler:["Konak","Bornova","Karşıyaka","Buca","Bayraklı","Karabağlar","Aliağa","Balçova","Bayındır","Bergama","Beydağ","Çeşme","Çiğli","Dikili","Foça","Gaziemir","Güzelbahçe","Karaburun","Kemalpaşa","Kınık","Kiraz","Menderes","Menemen","Narlıdere","Ödemiş","Seferihisar","Selçuk","Tire","Torbalı","Urla"]},
  {ad:"Kahramanmaraş",ilceler:["Dulkadiroğlu","Onikişubat","Afşin","Andırın","Çağlayancerit","Ekinözü","Elbistan","Göksun","Nurhak","Pazarcık","Türkoğlu"]},
  {ad:"Karabük",ilceler:["Merkez","Eflani","Eskipazar","Ovacık","Safranbolu","Yenice"]},
  {ad:"Karaman",ilceler:["Merkez","Ayrancı","Başyayla","Ermenek","Kazımkarabekir","Sarıveliler"]},
  {ad:"Kars",ilceler:["Merkez","Akyaka","Arpaçay","Digor","Kağızman","Sarıkamış","Selim","Susuz"]},
  {ad:"Kastamonu",ilceler:["Merkez","Abana","Ağlı","Araç","Azdavay","Bozkurt","Çatalzeytin","Cide","Daday","Devrekani","Doğanyurt","Hanönü","İhsangazi","İnebolu","Küre","Pınarbaşı","Seydiler","Şenpazar","Taşköprü","Tosya"]},
  {ad:"Kayseri",ilceler:["Kocasinan","Melikgazi","Talas","Akkışla","Bünyan","Develi","Felahiye","Hacılar","İncesu","Özvatan","Pınarbaşı","Sarıoğlan","Sarız","Tomarza","Yahyalı","Yeşilhisar"]},
  {ad:"Kilis",ilceler:["Merkez","Elbeyli","Musabeyli","Polateli"]},
  {ad:"Kırıkkale",ilceler:["Merkez","Bahşili","Balışeyh","Çelebi","Delice","Karakeçili","Keskin","Sulakyurt","Yahşihan"]},
  {ad:"Kırklareli",ilceler:["Merkez","Babaeski","Demirköy","Kofçaz","Lüleburgaz","Pehlivanköy","Pınarhisar","Vize"]},
  {ad:"Kırşehir",ilceler:["Merkez","Akçakent","Akpınar","Boztepe","Çiçekdağı","Kaman","Mucur"]},
  {ad:"Kocaeli",ilceler:["İzmit","Gebze","Başiskele","Çayırova","Darıca","Derince","Dilovası","Gölcük","Kandıra","Karamürsel","Kartepe","Körfez"]},
  {ad:"Konya",ilceler:["Karatay","Meram","Selçuklu","Ahırlı","Akören","Akşehir","Altınekin","Beyşehir","Bozkır","Cihanbeyli","Çeltik","Çumra","Derbent","Derebucak","Doğanhisar","Emirgazi","Ereğli","Güneysınır","Hadim","Halkapınar","Hüyük","Ilgın","Kadınhanı","Karapınar","Kulu","Sarayönü","Seydişehir","Taşkent","Tuzlukçu","Yalıhüyük","Yunak"]},
  {ad:"Kütahya",ilceler:["Merkez","Altıntaş","Aslanapa","Çavdarhisar","Domaniç","Dumlupınar","Emet","Gediz","Hisarcık","Pazarlar","Simav","Şaphane","Tavşanlı"]},
  {ad:"Malatya",ilceler:["Battalgazi","Yeşilyurt","Akçadağ","Arapgir","Arguvan","Darende","Doğanşehir","Doğanyol","Hekimhan","Kale","Kuluncak","Pütürge","Yazıhan"]},
  {ad:"Manisa",ilceler:["Şehzadeler","Yunusemre","Ahmetli","Akhisar","Alaşehir","Demirci","Gölmarmara","Gördes","Kırkağaç","Köprübaşı","Kula","Salihli","Sarıgöl","Saruhanlı","Selendi","Soma","Turgutlu"]},
  {ad:"Mardin",ilceler:["Artuklu","Dargeçit","Derik","Kızıltepe","Mazıdağı","Midyat","Nusaybin","Ömerli","Savur","Yeşilli"]},
  {ad:"Mersin",ilceler:["Akdeniz","Mezitli","Toroslar","Yenişehir","Anamur","Aydıncık","Bozyazı","Çamlıyayla","Erdemli","Gülnar","Mut","Silifke","Tarsus"]},
  {ad:"Muğla",ilceler:["Menteşe","Bodrum","Dalaman","Datça","Fethiye","Kavaklıdere","Köyceğiz","Marmaris","Milas","Ortaca","Seydikemer","Ula","Yatağan"]},
  {ad:"Muş",ilceler:["Merkez","Bulanık","Hasköy","Korkut","Malazgirt","Varto"]},
  {ad:"Nevşehir",ilceler:["Merkez","Acıgöl","Avanos","Derinkuyu","Gülşehir","Hacıbektaş","Kozaklı","Ürgüp"]},
  {ad:"Niğde",ilceler:["Merkez","Altunhisar","Bor","Çamardı","Çiftlik","Ulukışla"]},
  {ad:"Ordu",ilceler:["Altınordu","Akkuş","Aybastı","Çamaş","Çatalpınar","Çaybaşı","Fatsa","Gölköy","Gülyalı","Gürgentepe","İkizce","Kabadüz","Kabataş","Korgan","Kumru","Mesudiye","Perşembe","Ulubey","Ünye"]},
  {ad:"Osmaniye",ilceler:["Merkez","Bahçe","Düziçi","Hasanbeyli","Kadirli","Sumbas","Toprakkale"]},
  {ad:"Rize",ilceler:["Merkez","Ardeşen","Çamlıhemşin","Çayeli","Derepazarı","Fındıklı","Güneysu","Hemşin","İkizdere","İyidere","Kalkandere","Pazar"]},
  {ad:"Sakarya",ilceler:["Adapazarı","Akyazı","Arifiye","Erenler","Ferizli","Geyve","Hendek","Karapürçek","Karasu","Kaynarca","Kocaali","Pamukova","Sapanca","Serdivan","Söğütlü","Taraklı"]},
  {ad:"Samsun",ilceler:["Atakum","Canik","İlkadım","19 Mayıs","Alaçam","Asarcık","Ayvacık","Bafra","Çarşamba","Kavak","Ladik","Salıpazarı","Tekkeköy","Terme","Vezirköprü","Yakakent"]},
  {ad:"Siirt",ilceler:["Merkez","Baykan","Eruh","Kurtalan","Pervari","Şirvan","Tillo"]},
  {ad:"Sinop",ilceler:["Merkez","Ayancık","Boyabat","Dikmen","Durağan","Erfelek","Gerze","Saraydüzü","Türkeli"]},
  {ad:"Sivas",ilceler:["Merkez","Akıncılar","Altınyayla","Divriği","Doğanşar","Gemerek","Gölova","Hafik","İmranlı","Kangal","Koyulhisar","Suşehri","Şarkışla","Ulaş","Yıldızeli","Zara"]},
  {ad:"Şanlıurfa",ilceler:["Eyyübiye","Haliliye","Karaköprü","Akçakale","Birecik","Bozova","Ceylanpınar","Halfeti","Harran","Hilvan","Siverek","Suruç","Viranşehir"]},
  {ad:"Şırnak",ilceler:["Merkez","Beytüşşebap","Cizre","Güçlükonak","İdil","Silopi","Uludere"]},
  {ad:"Tekirdağ",ilceler:["Süleymanpaşa","Çerkezköy","Çorlu","Ergene","Hayrabolu","Kapaklı","Malkara","Marmaraereğlisi","Muratlı","Saray","Şarköy"]},
  {ad:"Tokat",ilceler:["Merkez","Almus","Artova","Başçiftlik","Erbaa","Niksar","Pazar","Reşadiye","Sulusaray","Turhal","Yeşilyurt","Zile"]},
  {ad:"Trabzon",ilceler:["Ortahisar","Akçaabat","Araklı","Arsin","Beşikdüzü","Çarşıbaşı","Çaykara","Dernekpazarı","Düzköy","Hayrat","Köprübaşı","Maçka","Of","Sürmene","Şalpazarı","Tonya","Vakfıkebir","Yomra"]},
  {ad:"Tunceli",ilceler:["Merkez","Çemişgezek","Hozat","Mazgirt","Nazımiye","Ovacık","Pertek","Pülümür"]},
  {ad:"Uşak",ilceler:["Merkez","Banaz","Eşme","Karahallı","Sivaslı","Ulubey"]},
  {ad:"Van",ilceler:["İpekyolu","Tuşba","Bahçesaray","Başkale","Çaldıran","Çatak","Edremit","Erciş","Gevaş","Gürpınar","Muradiye","Özalp","Saray"]},
  {ad:"Yalova",ilceler:["Merkez","Altınova","Armutlu","Çınarcık","Çiftlikköy","Termal"]},
  {ad:"Yozgat",ilceler:["Merkez","Akdağmadeni","Aydıncık","Boğazlıyan","Çandır","Çayıralan","Çekerek","Kadışehri","Saraykent","Sarıkaya","Şefaatli","Sorgun","Yenifakılı","Yerköy"]},
  {ad:"Zonguldak",ilceler:["Merkez","Alaplı","Çaycuma","Devrek","Ereğli","Gökçebey","Kilimli","Kozlu"]},
  {ad:"Aksaray",ilceler:["Merkez","Ağaçören","Eskil","Gülağaç","Güzelyurt","Ortaköy","Sarıyahşi","Sultanhanı"]},
  {ad:"Ardahan",ilceler:["Merkez","Çıldır","Damal","Göle","Hanak","Posof"]},
  {ad:"Bartın",ilceler:["Merkez","Amasra","Kurucaşile","Ulus"]},
  {ad:"Batman",ilceler:["Merkez","Beşiri","Gercüş","Hasankeyf","Kozluk","Sason"]},
  {ad:"Bayburt",ilceler:["Merkez","Aydıntepe","Demirözü"]},
  {ad:"Düzce",ilceler:["Merkez","Akçakoca","Cumayeri","Çilimli","Gölyaka","Gümüşova","Kaynaşlı","Yığılca"]},
  {ad:"Iğdır",ilceler:["Merkez","Aralık","Karakoyunlu","Tuzluca"]},
];

export const PARSIYEL = {
  "İstanbul": { renk:"#3B82F6", ilceler:[
    {ad:"Adalar",      lat:40.873,lng:29.120, yaka:"Anadolu"},
    {ad:"Arnavutköy",  lat:41.185,lng:28.739, yaka:"Avrupa"},
    {ad:"Ataşehir",    lat:40.992,lng:29.124, yaka:"Anadolu"},
    {ad:"Avcılar",     lat:40.979,lng:28.722, yaka:"Avrupa"},
    {ad:"Bağcılar",    lat:41.040,lng:28.857, yaka:"Avrupa"},
    {ad:"Bahçelievler",lat:40.998,lng:28.858, yaka:"Avrupa"},
    {ad:"Bakırköy",    lat:40.981,lng:28.874, yaka:"Avrupa"},
    {ad:"Başakşehir",  lat:41.093,lng:28.802, yaka:"Avrupa"},
    {ad:"Bayrampaşa",  lat:41.046,lng:28.911, yaka:"Avrupa"},
    {ad:"Beşiktaş",    lat:41.042,lng:29.007, yaka:"Avrupa"},
    {ad:"Beykoz",      lat:41.132,lng:29.109, yaka:"Anadolu"},
    {ad:"Beylikdüzü",  lat:40.979,lng:28.643, yaka:"Avrupa"},
    {ad:"Beyoğlu",     lat:41.033,lng:28.977, yaka:"Avrupa"},
    {ad:"Büyükçekmece",lat:41.018,lng:28.575, yaka:"Avrupa"},
    {ad:"Çatalca",     lat:41.143,lng:28.463, yaka:"Avrupa"},
    {ad:"Çekmeköy",    lat:41.041,lng:29.184, yaka:"Anadolu"},
    {ad:"Esenler",     lat:41.044,lng:28.876, yaka:"Avrupa"},
    {ad:"Esenyurt",    lat:41.028,lng:28.676, yaka:"Avrupa"},
    {ad:"Eyüpsultan",  lat:41.055,lng:28.933, yaka:"Avrupa"},
    {ad:"Fatih",       lat:41.019,lng:28.940, yaka:"Avrupa"},
    {ad:"Gaziosmanpaşa",lat:41.066,lng:28.912,yaka:"Avrupa"},
    {ad:"Güngören",    lat:41.021,lng:28.878, yaka:"Avrupa"},
    {ad:"Kadıköy",     lat:40.983,lng:29.080, yaka:"Anadolu"},
    {ad:"Kağıthane",   lat:41.083,lng:28.971, yaka:"Avrupa"},
    {ad:"Kartal",      lat:40.911,lng:29.186, yaka:"Anadolu"},
    {ad:"Küçükçekmece",lat:41.000,lng:28.776, yaka:"Avrupa"},
    {ad:"Maltepe",     lat:40.935,lng:29.149, yaka:"Anadolu"},
    {ad:"Pendik",      lat:40.876,lng:29.257, yaka:"Anadolu"},
    {ad:"Sancaktepe",  lat:41.002,lng:29.232, yaka:"Anadolu"},
    {ad:"Sarıyer",     lat:41.167,lng:29.057, yaka:"Avrupa"},
    {ad:"Silivri",     lat:41.073,lng:28.247, yaka:"Avrupa"},
    {ad:"Sultanbeyli", lat:40.962,lng:29.267, yaka:"Anadolu"},
    {ad:"Sultangazi",  lat:41.107,lng:28.883, yaka:"Avrupa"},
    {ad:"Şile",        lat:41.176,lng:29.611, yaka:"Anadolu"},
    {ad:"Şişli",       lat:41.060,lng:28.988, yaka:"Avrupa"},
    {ad:"Tuzla",       lat:40.818,lng:29.300, yaka:"Anadolu"},
    {ad:"Ümraniye",    lat:41.016,lng:29.117, yaka:"Anadolu"},
    {ad:"Üsküdar",     lat:41.023,lng:29.015, yaka:"Anadolu"},
    {ad:"Zeytinburnu", lat:41.003,lng:28.906, yaka:"Avrupa"}
  ]},
  "Tekirdağ": { renk:"#10B981", ilceler:[
    {ad:"Süleymanpaşa",lat:40.977,lng:27.513},{ad:"Çerkezköy",lat:41.288,lng:28.003},{ad:"Çorlu",lat:41.159,lng:27.800},
    {ad:"Ergene",lat:41.320,lng:27.950},{ad:"Hayrabolu",lat:41.214,lng:27.101},{ad:"Kapaklı",lat:41.340,lng:27.970},
    {ad:"Malkara",lat:41.295,lng:26.896},{ad:"Marmaraereğlisi",lat:40.969,lng:27.961},{ad:"Muratlı",lat:41.169,lng:27.494},
    {ad:"Saray",lat:41.441,lng:28.119},{ad:"Şarköy",lat:40.615,lng:27.101}
  ]},
  "Edirne": { renk:"#F59E0B", ilceler:[
    {ad:"Merkez",lat:41.678,lng:26.556},{ad:"Enez",lat:40.726,lng:26.074},{ad:"Havsa",lat:41.550,lng:26.815},
    {ad:"İpsala",lat:40.919,lng:26.379},{ad:"Keşan",lat:40.858,lng:26.636},{ad:"Lalapaşa",lat:41.829,lng:26.730},
    {ad:"Meriç",lat:41.188,lng:26.399},{ad:"Süloğlu",lat:41.779,lng:26.905},{ad:"Uzunköprü",lat:41.271,lng:26.691}
  ]}
};

export const YALOVA = { lat: 40.650, lng: 29.267 };
